version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/dockerBuild/
    overwrit : true
    
hooks:
  AfterInstall:
    - location: scripts/start_docker.sh
      timeout: 300
      runas: root
